server:
  port: 8087
  servlet:
    context-path: '/ead-authuser/'

spring:
  application:
    name: ead-authuser-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true #desabilitando logs do jdbc
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: always

ead:
  api:
    url:
      course: 'http://ead-course-service/ead-course'

logging:
  level:
    com.ead: trace
    root: info
    org.springframework.web: debug
    org.hibernate: info

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost